import type { Metadata } from 'next';
import '@/styles/styles.scss';
import styles from './layout.module.scss';

export const metadata: Metadata = {
  title: 'Algolia Assignment — Nicolas Jesenberger',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={styles['body']}>{children}</body>
    </html>
  )
}
